Repository Lugdu84/plan-together, pull requests merged in 2023-09, with the labels that each got.

#26 feature-#23 Set up architecture
  app/error.tsx
  app/layout.tsx
  app/not-found.tsx
  app/page.tsx
  package.json
Labels: front-end, architecture

#29 Finalizing seeding data to DB
  prisma/seed.ts
Labels: database

#33 setup interfaces and fix prisma schema
  .eslintrc.json
  .prettierrc
  app/error.tsx
  app/globals.css
  app/interfaces/Event.ts
  app/interfaces/Invitation.ts
  app/interfaces/User.ts
  app/layout.tsx
  app/not-found.tsx
  app/page.tsx
  cypress.config.ts
  cypress/.eslintrc.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  jest.config.js
  next.config.js
  postcss.config.js
  prisma/seed.ts
  tailwind.config.ts
Labels: database, front-end, back-end, architecture

#35 Implementing PostgresSQL through Docker
  .gitignore
  README.md
  docker-compose.yml
  package.json
Labels: database, architecture

#36 Identity and Design Tokens
  app/assets/fonts/PlusJakartaSans/OFL.txt
  app/assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic[wght].ttf
  app/assets/fonts/PlusJakartaSans/PlusJakartaSans[wght].ttf
  app/assets/fonts/Rowan/Rowan-Variable.woff2
  app/assets/fonts/Rowan/Rowan-VariableItalic.woff2
  app/assets/styles/globals.css
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/utilities/typography.tsx
  package.json
  public/favicon.ico
Labels: front-end

#37 Display all events / activities
  app/components/ActivityCard.tsx
  app/interfaces/Activity.d.ts
  app/interfaces/Invitation.d.ts
  app/layout.tsx
  app/page.tsx
  app/plan-it/activities/page.tsx
  package.json
  prisma/migrations/20230915151655_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: front-end
